### PR TITLE
ALGO-567 spacy package creation

### PR DESCRIPTION
**Pull request by zeryx**
Should be fully functional as-is, needed as a pre-requisite for allenNLP and other NLP based projects (such as some of EY's stuff)

### CODE REVIEW

**Comment by zeryx** [comment]
should  be ready for review

**Comment by besirkurtulmus** [comment]
@zeryx any reason not to include every language that's available on spacy?

**Comment by zeryx** [comment]
That should be all of the languages, did I miss one? the `xx` lang doesn't actually work very well from what I could see.

**Comment by zeryx** [comment]
I intentionally only added the small models instead of the large ones, we can split up the package into small/large if we want to.

**Comment by besirkurtulmus** [comment]
@zeryx, I see. My comment was based on your docstring: `You may change the language at runtime, but bear in mind that you'll get hit with some performance loss.`

Didn't realize that you added all available languages.

**Comment by besirkurtulmus** [comment]
@zeryx, what's the size difference between using small & large models?

**Comment by zeryx** [comment]
https://spacy.io/models/en
35 MB / 115 MB / 812 MB

They don't talk much about using the advanced models, and I feel like for most use cases the small's will be sufficient - but I could be persuaded to create a second spacy package that installs the large models instead.

**Comment by besirkurtulmus** [comment]
@zeryx, I see. Definitely makes sense to add them later.

One question I have though is how do we want to add them? All in a single package, or individually?

**Review by besirkurtulmus — APPROVED** [review]
LGTM.

**Comment by zeryx** [comment]
> @zeryx, I see. Definitely makes sense to add them later.
> 
> One question I have though is how do we want to add them? All in a single package, or individually?
Good question, I don't think we gain much from breaking them up, at least now. But for large models, docker image size is a concern. I'll have to defer to @pmcq and @neildf for that one.

**Comment by pmcq** [comment]
i don't really have a preference without knowing things more specifically, but seems like all the small models are like 30MB which isn't much.  if the image layers are like, less than 400MB i wouldn't super worry about it, but we'll have to try it out and see too. i don't know anything about this tool or what people might typically end up using from it

**Comment by zeryx** [comment]
I think most folks are only going to need the small models - DL doesn't make much sense for NLP.

**Review by kennydaniel — APPROVED** [review]

**Pull request merged**
