### PR TITLE
[PSE-245] Package mirror arguments for use in IPA build and execution

### PR DESCRIPTION
**Pull request by dmorris-algo**
Five package mirror arguments are added to the _builder_ image; `CRAN_MIRROR` is passed into `langserver`'s environment during algorithm execution.

This supports both IPA algorithm builds and IPA algorithm executions:
- https://github.com/algorithmiaio/containers/pull/185
- https://github.com/algorithmiaio/docker-builder/pull/1
- https://github.com/algorithmiaio/node-autoscaler/pull/148

### CODE REVIEW

**Comment by pmcq** [comment]
don't worry about dockherder.  but also in general - why do we need the mirror args at runtime? I would expect that users aren't installing more packages at runtime than they already did at compile.  i think this might've been there because of some weirdness with R specifically, but the other languages can probably be removed (and hopefully we can remove R's too since it's sloooow)

**Review by zeryx — DISMISSED** [review]
LGTM, checked all workflows with `./tools/environment_validator.py` and nothing's broken in my world.

**Comment by aslisabanci** [comment]
Tested the branch by running a previously successful "environment validator" script run to build a Pytorch package and it was successful.

**Review by robert-close — DISMISSED** [review]

**Review by pmcq — APPROVED** [review]
:taco: :taco: :taco:

**Pull request merged**
