### PR TITLE
small typo fixes, no functionality affected

### PR DESCRIPTION
**Pull request by lemonez**
was reading through, figured I'd clean it up as I went :)

[PSE-XXX](https://algorithmia.atlassian.net/browse/PSE-XXX) - Brief description

Additional context about what's changing, design tradeoffs or issues, links to an epic or other PRs, etc.

## Checklist
- [ ] My PR title includes a relevant Jira ticket name
- [ ] If I made configuration changes, they are in the config template in the deploy directory
- [ ] I have added unit tests where appropriate
- [ ] I have added integration tests where appropriate
- [ ] Manual tests are required in a cluster

## Backporting
This will need to be merged into the following support branches:

### CODE REVIEW

**Review by aslisabanci — APPROVED** [review]
Love the attitude, thanks Ezra!

**Comment by lemonez** [comment]
@aslisabanci please merge, I don't have write access

**Review by aslisabanci — APPROVED** [review]

**Review by aslisabanci — APPROVED** [review]

**Comment by aslisabanci** [comment]
Hey @lemonez, why don't you make the changes directly on a branch of this repo, without forking? We need to kick off the CI job on a branch of this repo and get it succeed to enable merging.

**Comment by lemonez** [comment]
changes moved to PR 196, branch instead of fork.

**Pull request closed without merging**
